# -*- coding: utf-8 -*-
"""Convert_Color_Image_to_Sketch.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1vcd0PcYBJ-RtS_iYr262c4yVfofzkuAY
"""

#Install imageio package
!pip install imageio #provide an API to read and write the image data in various formats

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import imageio
import requests
import matplotlib.pyplot as plt
import IPython.display as dp

#Display the image from the web using an URI.
img="https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8bWFufGVufDB8fDB8fA%3D%3D&w=1000&q=80"
dp.Image(requests.get(img).content)

#Read the image using imgaeio package's imread method and URI from web using 
source_img = imageio.imread(img)

# Make the image Black and White using the formula Y= 0.299*R + 0.587*G + 0.114*B i.e. applying greyscale
import numpy as np
#this function calculate the weighted mean of RGB values of original image using this formula and will return the grayscale vesion of any color image
def grayscaleimg(rgb): 
  return np.dot(rgb[...,:3], [0.299, 0.587, 0.114])

gryscl_img = grayscaleimg(source_img)

#Invert the image by subtracting it from 255
inv_img = (255 - gryscl_img)
plt.imshow(inv_img)

#Blur the image using gaussian filter
#this filter is low pass filter used to remove  details & noise and to blur 
import scipy.ndimage  #n-dimensional image  it's a package contains functions for image processing
#and scipy library (scientific computation) has functions for optmization, signal processing
blurred_img = scipy.ndimage.filters.gaussian_filter(inv_img, sigma=5) #sigma is STD and it's the smoothing of filter 
#if we increase the value it becomes more blur
plt.imshow(blurred_img)

#Create function to perform dogding(belnding together greyscale and blurred image)
#dodging is used to lighten the important areas of the image 
def dodging(blur_img, gryscl_img):
    resultant_dodge=blur_img*255/(255-gryscl_img) 
    resultant_dodge[resultant_dodge>255]=255
    resultant_dodge[gryscl_img==255]=255
    return resultant_dodge.astype('uint8')

#Generate the target image by applying the dodge
target_img= dodging(blurred_img, gryscl_img)

# Commented out IPython magic to ensure Python compatibility.
#Display the target image
# %matplotlib inline
import matplotlib.pyplot as plt
plt.imshow(target_img, cmap="gray")

#Save the image
plt.imsave('target_image.png', target_img, cmap='gray', vmin=0, vmax=255)

